version: '3.7'

networks:
  loki:

services:

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - 3060:3000
    networks:
      - loki

  django_gunicorn:
    volumes:
      - static:/static
      # - './static:/app/static'
    env_file:
      - .env
    build: 
      context: .
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      # - './static:/app/static'
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"

volumes:
  static:
