global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
        # - app1:8000
        - host.docker.internal # 這一條單獨時可以跑 只是有錯

