# Generated by Django 4.0.3 on 2023-04-30 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fmsApp', '0003_historicalpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group'),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
