# Generated by Django 4.0.3 on 2023-04-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0004_historicalpost_group_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
